mvc/Models/Bookmark.cs
namespace mvc.Models
{
    public class Bookmark
    {
        public string Avatar_url { get; set; }
        public string Name { get; set; }
    }
}

mvc/Models/Items.cs
namespace mvc.Models
{
    public class Items
    {
        public string Name { get; set; }
        public Owner Owner { get; set; }
    }
}

mvc/Models/Owner.cs
namespace mvc.Models
{
    public class Owner
    {
        public string Avatar_url { get; set; }
    }
}

mvc/Models/Repository.cs
namespace mvc.Models
{
    public class Repository
    {
        public int Total_count { get; set; }
        public Items[] Items { get; set; }
    }
}

mvc/Controllers/BookmarksController.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class BookmarksController : Controller
    {
        //retrieve the stored bookmarks from session into a list

        [HttpGet]
        public ActionResult DisplayBookmarks()
        {
            List<Models.Bookmark> bookmarks = (List<Models.Bookmark>)Session["SavedBookmarks"];
            return View(bookmarks);
        }
    }
}

mvc/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using mvc.Models;

namespace mvc.Controllers
{
    public class HomeController : Controller
    {
        //home screen

        [HttpGet]
        public ActionResult ShowHomePage()
        {
            return View("MyHome");
        }
    }
}

mvc/Controllers/RepositoriesController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Net;
using mvc.Models;
using System.Configuration;

namespace mvc.Controllers
{
    public class RepositoriesController : Controller
    {
        //new repository search screen

        [HttpGet]
        public ActionResult GetJsonDataModel()
        {
            return View("SearchForRepository");
        }

        // get and render the repositories which came from GitHub api according to the word the user inserted

        [HttpPost]
        public ActionResult GetJsonDataModel(string searchText)
        {
            if (searchText.Length < 1)
                return View("SearchForRepository");
            else
            {
                var webClient = new WebClient();
                webClient.Headers.Add("user-agent", "repository");
                var json = webClient.DownloadString(ConfigurationManager.AppSettings["API_URL"].ToString() + searchText);
                Models.Repository objJson = JsonConvert.DeserializeObject<Repository>(json);
                return View(objJson);
            }
        }

        //store the bookmarked repositories in session

        [HttpPost]
        public ActionResult SaveToSession(string AvatarURL, string Name)
        {
            List<Models.Bookmark> bookmarks = new List<Bookmark>();
            Models.Bookmark bookmark = new Bookmark();
            bookmark.Avatar_url = AvatarURL;
            bookmark.Name = Name;
            if (Session["SavedBookmarks"] != null)
            {
                bookmarks = (List<Bookmark>)Session["SavedBookmarks"];
            }
            bookmarks.Add(bookmark);
            Session["SavedBookmarks"] = bookmarks;
            return RedirectToAction("GetJsonDataModel", "Repositories");
        }
    }
}

mvc/Views/Bookmarks/DisplayBookmarks.cshtml
@model IEnumerable<mvc.Models.Bookmark>
@{
    ViewBag.Title = "DisplayBookmarks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2>BOOKMARKED REPOSITORIES</h2>
<br />
<br /><br />

@{
//if list has bookmarks in it-display

    if (Model != null)
    {
        foreach (var item in Model)
        {
            <div>
                <h5><u>Avatar URL:</u></h5>
                @item.Avatar_url
                <h5><u>Name:</u></h5>
                @item.Name
                <br /><br />
                <hr />
            </div>
        }
    }
}
<br /><br />
<br /><br />
<br /><br />
<br /><br />

mvc/Views/Home/myHome.cshtml
@{
    ViewBag.Title = "MyHome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>My Home</title>
</head>
<body>
    <div>
        <br />
        <h2>WELCOME TO OUR REPOSITORY SEARCH APPLICATION</h2>
        <br />
        <h5>CHOOSE <b>VIEW GALLERY</b> TAB FOR A NEW SEARCH</h5>
        <h5>CHOOSE <b>BOOKMARKED REPOSITORIES</b> TAB TO VIEW YOUR BOOKMARKED REPOSITORIES</h5>
    </div>
    <br /><br />
    <br /><br />
    <br /><br />
    <br /><br />
</body>
</html>

mvc/Views/Repositories/GetJsonDataModel.cshtml
@model mvc.Models.Repository
@{
    ViewBag.Title = "GetJsonDataModel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2>REPOSITORY SEARCH</h2>
<br />

@using (Html.BeginForm("GetJsonDataModel", "Repositories"))

//getting the word for search
{
    <h4>Please insert a word for search:</h4>
    <input type="text" name="searchText" />
    <input type="submit" value="Submit" />
}

<br /><br />

@{
    foreach (var item in Model.Items)
    {
      <div>
          <h5><u>Avatar URL:</u></h5>
          @item.Owner.Avatar_url
          <h5><u>Name:</u></h5>
          @item.Name
          <br /><br />

          @using (Html.BeginForm("SaveToSession", "Repositories"))
          {
              <input type="hidden" name="AvatarURL" value=@item.Owner.Avatar_url />
              <input type="hidden" name="Name" value=@item.Name />
              <input type="submit" value="Bookmark" />
          }
          <hr />
      </div>
    }
}
<br /><br />
<br /><br />
<br /><br />
<br /><br />

mvc/Views/Repositories/SearchForRepository.cshtml
<br />
<h2>REPOSITORY SEARCH</h2>
<br />


@using (Html.BeginForm())
{
    //getting the word for search

    <h4>Please insert a word for search:</h4>
    <input type="text" name="searchText" />
    <input type="submit" value="Submit" />
}

<br /><br />
<br /><br />
<br /><br />
<br /><br />

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Repositories Gallery</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("View Gallery", "GetJsonDataModel", "Repositories")</li>
                    <li>@Html.ActionLink("Bookmarked Repositories", "DisplayBookmarks", "Bookmarks")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>